### ISSUE TITLE
[뉴스레터] form -> stibee

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#10]
![스크린샷 2021-10-20 오후 3 55 11](https://user-images.githubusercontent.com/6022883/138042925-86d30245-e40c-429f-8c80-0a5c759d8405.png)

- team durumi stibee 계정으로 테스트 및 구현
- production 은 박물관 계정(vault) / 박물관 뉴스레터는 정의연 뉴스레터와 동일

**Comment by woonjjang** [comment]
오오 !!  테스트 확인했습니다. 
실서버는 참고해서 링크들만 바꿔서 배포하겠습니다.

**Comment by mozodev** [comment]
1. 운영에 배포하려면 일단 어떤 리스트에 구독자를 쌓을지 결정해야하고
2. 뉴스레터도 어떤 걸 목록에 뿌릴건지 결정해야합니다.

**Comment by mozodev** [comment]
리모트 리소스 fetch 오류는 수정했는데 구현하다 보니 문제가....
아래처럼 스티비 뉴스레터 아카이브 페이지는 구독자 목록 아이디 기준으로 보여주는데요...
https://page.stibee.com/archives/105093
왜 1개 뿐인지... 이상하게 되어 있습니다. ㅎㅎ 이러면 뉴스레터 보낼 때 마다 하나하나 추가해줘야해서 번거로운데...

**Comment by woonjjang** [comment]
[뉴스레터 관련]
- 아카이브 페이지 업데이트 완료 https://page.stibee.com/archives/105093
- 78명 있는 "뉴스레터 구독 목록" https://stibee.com/lists/112752

**Comment by woonjjang** [comment]
1. 잘 수집되고 있었는데, 중복된 이메일이 있을 때 생기는 undefine 메세지 
- https://github.com/team-durumi/theme-wwm/commit/1d31e5afb3bd5755d39af0fa1940265747332d5f
2. 스티비 관리창에서 확인이메일 설정을 하는지 / 아닌지에 따라 action이 다름 (고객 확인 후 변경)
