### ISSUE TITLE
[Form] 4개 메뉴

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#14]
### Form to email
- [x] 기록물 이용신청 - 좀 복잡한 문서라 이 메뉴는 스태틱으로 돌릴 수 있음. -> 안내방식으로
- [x] 기록물 기증신청 - https://womenandwarmuseum.net/archive/donate/
- [x] 자원활동 신청 - https://womenandwarmuseum.net/connect/volunteer/ (자원활동을 받지 않는 기간에 form을 숨기는 on/off 필터를 요청했음.)

### Form to Front (데이터 저장 영역을 결정하진 않았음.)
- [x] 온라인 교육 - 나비메세지 https://womenandwarmuseum.net/research-and-learning/e-learning/ -> https://github.com/team-durumi/theme-wwm/issues/12
- [ ] 나비메세지 노출되는 영역 디자인 필요 (확정 안 됨.) -> https://github.com/team-durumi/theme-wwm/issues/12

3개 메뉴에 폼 들어가고 이메일로 받는 것까지 수용해줄까해요. 의견주셔도.
https://durumi.io/contact 개발하는데, bot validation 하는 부분까지는 들어가면 좋을 듯 합니다.
![스크린샷 2021-11-03 오후 1 59 10](https://user-images.githubusercontent.com/6022883/140012239-3dcc8f37-da8a-462e-96e5-9d2b3d3bef74.png)

**Comment by suncrud** [comment]
뭐 하나 골라야할거 같은데 steinhq로 돌릴까요?
어제 모조님이랑 잠깐 얘기했는데 구글폼은 공식적인 api가 없는듯

**Comment by woonjjang** [comment]
코드에는 formspark 코드만 참조한거고, json 형식만 맞으면 잘 들어간답니다. 
steinhq로 돌려도 좋음.

**Comment by mozodev** [comment]
서비스 늘리지 않는 걸로 하면 netlify form이 좋을 것 같기는 한데...
https://www.netlify.com/pricing/#add-ons-forms 
무료는 한 달에 100번 요청을 처리... 오류, 스팸등 생각하면 부족할 듯...

- https://edcupaioli.com/blog/google-form-front-end/
- https://github.com/jsdevel/google-form/blob/master/google-form.js

이런 글을 보니 구글 폼 URL/formResponse 요렇게 하면 요청을 받아주는듯? ㅎ

**Comment by mozodev** [comment]
참 이거 구글 폼과 데이터시트는 고객이 만들어놓은게 있는걸까요? 우리가 만들고 권한 줌?

- 기록물 기증신청 content/archive/donate.md
- 자원활동 신청 content/connect/volunteer.md
- 온라인 교육 - 나비메세지  content/research-and-learning/e-learning.md

**Comment by suncrud** [comment]
>     * https://github.com/jsdevel/google-form/blob/master/google-form.js

저도 이거 바탕으로 작업중이었는데, 요새는 /formResponse 에 나오는게 좀 달라졌나보더라구요.

* 체크박스 요소는 'entry.난수_sentinel' 요렇게 되어있고 (가이드에는 _sentinel 안붙어있음)
* textarea는 이런 요소가 없음 

그래서 이게 공식이 아닌거 같애서 바뀌면 노답이지 않을까 하는 문제의식이..

**Comment by mozodev** [comment]
```
# parmas.yml

google:
  forms:
    "archive/donate": {{ form_id }}
    "connect/volunteer": {{ form_id }}
    "research-and-learning/e-learning": {{ form_id }}
```
- [ ] 구글 폼 만들어서 각 아이디를 접근할 수 있게 params.yml에 추가해놓고 시작하면 좋겠네요.


현재는 shortcode를 페이지 path 따라서 구성한 거 같은데 폼이 여러 곳에서 사용될 수 있으니 폼 파셜을 한군데 모으면...

`{{< archives/form--donate-materials >}}` => `{{< form id="donate-materials" >}}`

- [ ] shortcode에 제목 넘겨서 partial 출력하게 재구성. form 파셜 위치는 `layouts/parials/feedbacks/`

**Comment by suncrud** [comment]
> @mozodev 어떤 툴을 쓸지 확정된게 아닌게 있고, 구글 계정 owner가 아닌 경우에 구글 form, excel 접근이 안 되는 경우도 있어서 우리쪽 엑셀에 구현 해 놓고, production에서 배포할 때 교체할까합니다. (썬이랑은 지난번에 그렇게 상의했어요. )

받는 포맷도 포맷인데, 제 질문의 요지는 구글폼 공식 api가 아직 미비하다. (찾아보니 얼리버드 whitelist 신청해야하는 [forms api beta](https://developers.google.com/forms/api)는 있음 )

일단 구글 폼이랑 구글 스프레드시트는 개념상 분리가 필요할거 같구요. 
엔드포인트를 구글스프레드시트로 해서 stein API를 쓰자 아님 뭐 다른 API를 쓰자 뭐 이런식으로 합의가 필요하지 않을까 하는 생각이 들어서요. 

운짱 얘기대로 일전에 우리 구글계정에 구현해놓고 바꾸자고 했을때도, 교체할때 소요가 적어야될거같다는 생각이 들긴 해서 쓰는 API도 확정을 좀 해야되지 않나 생각이 듭니다.

**Comment by mozodev** [comment]
음 테스트해보니 구글 폼을 사용하는 거.. 아직 성공도 못했고 상당히 번거롭군요.
steinhq 무료 플랜은 한달 5000 요청에 시트당 200 줄... 
200개 넘으면 시트 아이디를 바꿔줘야함? ㅎ 이것도 못 쓰겠...
https://steinhq.com/pricing
그럼 결국 귀찮지만 만들어야하는...? ㅎ

**Comment by suncrud** [comment]
정리하면 구글 스프레드 시트에 입력되는 api를 만들면 되는거겠죠?

**Comment by mozodev** [comment]
검색하다가 이런 걸 보게 되어서
https://api.steinhq.com/v1/storages/5e6e3e9fb88d3d04ae08158c/Hospitals?ref=https://githubhelp.com

이걸 보고 있었....
https://docs.steinhq.com/self-hosting

**Comment by suncrud** [comment]
아 맞아요 ㅎ 쓰게되면 셀프호스팅하면 되겠다 해놓고 위에 답변할때 까먹었..
