### ISSUE TITLE
UI 관련 해결 및 도움(QA)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#22]
[이슈]
- 버그일 수도 있고, UI 만들어주신 것을 잘 못 붙였을 수도 있어요. 
- https://stage.womenandwarmuseum.net/ (배포된 곳에서 확인)

## 1. 소장품 목록 스크립트 로드 문제
- html에서는 잘 로드됨. 
- 메인
- 소장품 https://stage.womenandwarmuseum.net/items/
![item-script](https://user-images.githubusercontent.com/6022883/146904948-f419676c-d49a-4123-bf61-5b3d44f2dbb3.png)

## 2. 메가 메뉴
- 하얀색 배경보다 텍스트가 먼저 로드됨. 
![스크린샷 2021-12-19 오후 3 21 11](https://user-images.githubusercontent.com/6022883/146905131-9a1280b8-32db-4de9-a72e-9f282036cdf4.png)

**Comment by css3studio** [comment]
1번 이슈는 이미지 로딩이 늦어지면서 발생하는 일반적인 문제입니다. 일반 JS를 사용하면 비교적 간단하게 해결이 가능합니다만, AlpineJS는 연구를 해봐야 겠네요

**Comment by css3studio** [comment]
2번 이슈는 해결하여 푸시하였습니다.

**Comment by woonjjang** [comment]
![홈](https://user-images.githubusercontent.com/6022883/147305997-422b8d66-d9c5-46a2-bd22-b1312f722784.png)

### 디자인 요소 
- 메인 홈 헤더 (@css3studio 피그마 최종 디자인이었는데, 전달이 늦었었나봐요.)
- [x]  서브 메뉴가 내려올 때 텍스트와 배경 타이밍 맞추기(현재 텍스트가 한 템포 빠름)
- [ ]  서브 내려오는 것 부드럽게 바꾸기
- [ ]  서브 개별 하이라이트 시 글자에 규격 맞추지 않고 좌우 서브 메뉴 가운데를 기준으로 여백 두기
- [ ]  (작업 중이시겠지만,,) 검색 아이콘만 남겨두기
    
### 메인홈 뉴스레터 
- 뉴스레터(기존 게시판 유지) 
    - [ ]  메인 홈에 뉴스레터 신청 필드란 주변(텍스트, 사진)을 눌렀을 때 뉴스레터 게시판으로 이동할 수 있도록 링크 연결(디자인 ) @calvin-design 

### 메인홈 뉴스레터
- [ ]  영어 / 일어 사용자를 위한 가이드 추가 (메인 추가) / 두루미팀에서 re-design 적용 @calvin-design

**Comment by css3studio** [comment]
서브 개별 하이라이트 시 글자에 규격 맞추지 않고 좌우 서브 메뉴 가운데를 기준으로 여백 두기
-> 혹시 가능하면 디자인 변경 고려 부탁드려요. 현재 개발환경에서 양쪽에 여백을 두는게 좀 쉽지 않아 보입니다.
hover시에 색상변경이나 밑줄 보이게 하는 방식들 고려 부탁합니다.

**Comment by css3studio** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/30469662/147307739-be4257e9-9114-439c-adf3-d0ac2052cdb1.png">
검색 부분은 저'검색'텍스트를 삭제하면 바로 적용됩니다

**Comment by woonjjang** [comment]
QA 전체 목록 공유합니다. 필터링해서 이슈로 남길께요. (team@durumi.io) 계정으로 접근 가능
https://www.notion.so/86c93e5c67644240977601fce7f5f649?p=568f52b627b2442eb09a61dfb60d3686

**Comment by css3studio** [comment]
“서브 내려오는 것 부드럽게 바꾸기” 는 내려오는 속도 조정 요청인가요? 아니면 효과를 바꿔달라는 요청인가요?

**Comment by woonjjang** [comment]
> “서브 내려오는 것 부드럽게 바꾸기” 는 내려오는 속도 조정 요청인가요? 아니면 효과를 바꿔달라는 요청인가요?
이건 거절하려고 했는데, 약간 속도를 느리게 맞춰보면 어떨까해요.

**Comment by css3studio** [comment]
메가메뉴 내려오는 효과 > ease-linear로 변경하였습니다. 요걸로 한번 보여줘봐 주세요

**Comment by css3studio** [comment]
"서브 개별 하이라이트 시 글자에 규격 맞추지 않고 좌우 서브 메뉴 가운데를 기준으로 여백 두기" - 해결하여 푸시하였습니다. 마크업은 안고치고 css만 업데이트해도 적용됩니다. 고치면 더 좋구요

**Comment by css3studio** [comment]
1.소장품 목록 스크립트 로드 문제 -> Masonry를 기존 스크립트 방식에서 css 구현으로 변경하였습니다.
