### ISSUE TITLE
[hugofy]검색 레이아웃 붙이기

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#24]
https://github.com/css3studio/warwomens/commit/b75b7f05e9680b6d93856c30cce31aab97ff1e7a

검색

**Comment by woonjjang** [comment]
@suncrud 잘 안 되면 채널이나 DM으로 알려주세요.

**Comment by woonjjang** [comment]
@suncrud 검색 작동하는 것을 본 것 같은데, 테마에서도 wwm에서도 작동이 잘 안 되네 확인만 한 번 부탁드려요.

**Comment by suncrud** [comment]
스테이지에서는 잘 작동하는거 같은데 실서버에서는 자바스크립트 로드 이슈가 있는듯?

**Comment by mozodev** [comment]
오류를 확인하는 과정을 훈련해야겠네요 ㅎ
우리는 엔지리어링을 하는 사람들이니까 원인을 파악해야 합니다. 
인문학적, 종교, 예술적 상상, 추측이나 저절로 그냥 되는거는 우리가 일하는 세계에는 없습니다. 이건 확실히 믿어도 됨.

브라우저에서 오류를 확인하려면 무조건 cmd + shift + i => 브라우저 개발도구 console, network 등 탭을 확인합시다!
https://womenandwarmuseum.net/search/?q=%EC%A0%84%EC%8B%9C

```
GET https://womenandwarmuseum.net/js/libs/fuse.js/3.2.1/fuse.min.js net::ERR_ABORTED 404
womenandwarmuseum.net/:211 GET https://womenandwarmuseum.net/js/libs/mark.js/9.0.0/mark.min.js net::ERR_ABORTED 404
womenandwarmuseum.net/:212 GET https://womenandwarmuseum.net/js/search.js?%25!s%28MISSING%29 net::ERR_ABORTED 404
womenandwarmuseum.net/:210 GET https://womenandwarmuseum.net/js/libs/fuse.js/3.2.1/fuse.min.js net::ERR_ABORTED 404
womenandwarmuseum.net/:211 GET https://womenandwarmuseum.net/js/libs/mark.js/9.0.0/mark.min.js net::ERR_ABORTED 404
womenandwarmuseum.net/:212 GET https://womenandwarmuseum.net/js/search.js?%25!s%28MISSING%29 net::ERR_ABORTED 404
```

원인을 찾았으면 수정합니다~

**Comment by mozodev** [comment]
https://app.netlify.com/sites/women-war-museum/settings/deploys

```
huod mod tidy && hugo --gc --minify
=>
hugo mod get -u ./... && hugo --gc --minify
# and trigger deploy
```

했으나 코드에 빌드 커맨드 박아놨다고 그걸 사용한다고 함.

**Comment by mozodev** [comment]
https://womenandwarmuseum.net/search/?q=%EC%A0%84%EC%8B%9C ㅎㅎ
