### ISSUE TITLE
[QA] UI 관련

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#25]
[개선]
- [x] 메인 네비게이션 위 영문 / 일문 1줄 들어간 영역
- [x] 메인 공지사항 얇은 바에 관람예약 버튼
- [x] 연혁 날짜부분 텍스트에 따라 레이아웃 깨지는 부분
- [x] 관람 안내  막대기 옆으로 하위 내용 옮기기(아래처럼, 왼쪽 구분 바를 길게 하여도 괜찮습니다)
- [x] 특별전시 연혁 좌우 데이터 구분할 수 있도록 처리(특별전시-섹션1)

[빠진것]
- [x] 특별전시 메세지 뿌리는 방법 (섹션 3)
- [x] 관람 및 예약 (카카오톡 공유버튼) -> 개발 반영
- [x] 게시글 세부에서 목록 돌아가기 버튼

특별전시 메세지 뿌리는 방법 >> 요건 협의가 필요하시면 콜을 잠깐 해도 좋습니다.

**Comment by woonjjang** [comment]
관람안내
![스크린샷 2021-12-29 오후 1 36 35](https://user-images.githubusercontent.com/6022883/147627799-c1a99bb0-fda9-4bbe-a748-ab377a552a46.png)

특별전시
![스크린샷 2021-12-29 오후 1 28 51](https://user-images.githubusercontent.com/6022883/147627811-b887dc23-ca6c-45e6-86af-58f0985e47fb.png)

**Comment by woonjjang** [comment]
![스크린샷 2022-01-03 오후 4 37 07](https://user-images.githubusercontent.com/6022883/147908056-978916b9-9bd3-4113-bfce-42ecaf83f993.png)

**Comment by woonjjang** [comment]
<img width="321" alt="스크린샷 2022-01-03 오후 11 56 58" src="https://user-images.githubusercontent.com/6022883/147945526-8ec03731-480d-4a53-a098-20a939d902d1.png">
@css3studio 모바일은 요 버전으로 가시죠. ~

**Comment by css3studio** [comment]
메인 네비게이션 위 영문 / 일문 1줄 들어간 영역 완료하여 푸시하였습니다.
메인은 index.html, 서브는 about-donate.html 참고하시면 됩니다.

그리고, 메가메뉴 스크립트도 좀 조정하였습니다. 마우스가 2뎁스 영역에 들어가도 메뉴가 열리는 문제가 발견되어 수정하였습니다.

**Comment by css3studio** [comment]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/30469662/148332652-eb4ac8b6-49e5-4de4-ac1a-21ca696b555d.png">

특별전시 메세지 뿌리는 방법 (섹션 3) 구현 시 표시한 값들을 조정하시면 됩니다.

**Comment by woonjjang** [comment]
@css3studio 현민님 작업 감사합니다. 
https://github.com/css3studio/warwomens/commit/14cb8df0df394bf30a516ae6b69145fea18707d2

폰트 저작권 때문에 이미지로 넣기는 어려울 것 같아요. img 영역에 그냥 텍스트 영역으로 넣을 수 있도록 잡으면 좋을 것 같습니다. 
그부분만 수정해주시면 감사하겠습니다. (큰 제목 + 중간제목 + 본문 3개 영역 정도만)

**Comment by css3studio** [comment]
텍스트로 수정해서 올렸습니다~
