### ISSUE TITLE
전시세부02번 템플릿 슬라이더 옆에 텍스트 요소에 대한 고민

### ISSUE THREAD

**Issue by suncrud** [team-durumi/theme-wwm#28]
현재 구현 상태: https://stage.womenandwarmuseum.net/exhibition/ex-00/section-view02_sample/ 

전시섹션 세부02 템플릿을 보면 이미지 슬라이더와 그 우측에 설명 부분으로 되어있습니다. 
@css3studio 님이 주신 [템플릿](https://github.com/css3studio/warwomens/blob/main/html/exhibit-section-view02.html)을 보면 이미지 슬라이더가 돌고, 언급된 텍스트는 고정으로 되어있는데요. 

전시01 템플릿 디자인을 보면 이미지 요소마다 캡션이 달도록 되어있는것 처럼 전시02 템플릿도 슬라이드되는 이미지마다 텍스트가 같이 대응되어서 이미지 바뀔때마다 텍스트도 바뀌어야 할거라고 생각했는데요,

생각해보니 기획적으로 맞는지 확신은 안서가지고.. 확인이 필요할 것 같습니다.

제 말이 맞다면 슬라이드에 맞춰서 텍스트 요소도 돌아야 될거 같아요. 

확인 부탁드려요

**Comment by mozodev** [comment]
https://github.com/css3studio/warwomens/tree/main/html
https://warwomens.netlify.app/html/exhibit-section-view02.html

**Comment by woonjjang** [comment]
@suncrud fade in 효과로 바꿔서, 왼쪽 슬라이드가 변 할 때 오른쪽 타이틀 / 설명 부분도 교체되는 방식으로 업데이트 요청드렸습니다.

**Comment by css3studio** [comment]
수정하여 올렸습니다

**Comment by suncrud** [comment]
@css3studio 감사합니다 현민님!
